language: node_js
node_js:
  - '13'
  - '12'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run lint
  - yarn run build
before_deploy:
  - cd dist/ngx-sentry
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: RbcxdcfklJKiIXv2Q7llnt9ebbiEMmoXDZRVPY6824UII3+Y+wxp5sbOEULfOFPUGw9QFB4bE1KgrsibnJUcX9ca3NqOcQ7F+BRx5M2zwDXfINTmV+Agtdm/rQKBozHEdiVzMf93u/HnMVygXT402FwsfOSErYFvaKjEXlIsqwrKxPvmHcJWMv4jappjuwahe4CHALwTudJ1CZjbsPR7lFqDDUrAgOLn8zJ0yZAAV50/+d0DdSms1mynhKrDrv6FJngFZJv4thLdzBlJ7daEOXDW8PAHIY/cjBkO0z3eq11B/EeaAnRyxUW3y7e7d6q35gawuVO8ntm0yhTduoI2huhcavWjUsCWZmC/keLLN5bVWRFsuioq6lenwxWHIjFhT+p+K9ielI3WFYYChHDTl0AxHj1DiJrhagg6Iwii5lQQfXpb4/a5rwPZEtAHtdbjFjFHWBoQJpwrDH/n7ABT0yAchy8CpefPc32ErTyAMWOZXJ/0/IpRSdR4bJthD37EoKBLFP1/qqe7eYNqpHSHHPvYRJBpEDz+1xqJgJ9r3DjuZ856bMsllKPgZmeU+9MC0CpY/A5H9VCw6vBDesunRQpMiE2bKVEnqrax/YvPs1uo3YCW/LHLA7C4KI8xDdcFbqVfqzWeN1P5aPHuyg37hAnGs1n5dGxyv5XqFHDEFrc=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 13
notifications:
  slack:
    rooms:
      - secure: eWI+L5YntaVGB1ydN2rNeurwBLsTYVMLFYvfPGe67i3pFmvWLJjXW3wrU92sPf8w1/6HvqBk+Dnr1FJDXaRsJzw/9NNqI7kFH2069HSWR5pnfBIQBakr1a6jLt5xxtDgqYex534Ajz1B6GvIq0Gxvk0+FXQIZjdbc6xnC0wEQhq1BKQrsWkx5dVcSIfF3KmUW2KS2qELPp3VHT9hKs/djUsZnEo2VvknDSksMbVReb8Ys2WaHxtJhiBXhYqSVg6VL6AJHJN+MK/CgdSzvygBBC7IymSau4cYWpUemcQfEH+rIxluZj6dfIWnNbdwYbHD45sbs7cy1wdKtCrnR/UgyZ0Y8wDfETkWcv5X37hjKyeTwrpdKdR2xsIJVaNFumcoPB4GTu8RGMvI9CB1j8gxgdXoJ0FLUQ3Wp6WpXYfF7nCpmyvo8bb3CelGcjKbYxs44tAFHtHaZpfML1PKkRHpBs8+DihBbGQkLuxOmYnFHNihCUbbjb5QCx2ufSU6VncbP/MUoqmR2OUgNpUpAc4d0k5UGKOJfqqvx9+44MsIWfHcEsjku1HTeBpZRQvZvqvSzkXmF2PIiKn1oAg8M7ePlC3SAmXkadsKnxdjFPjWxGLK27Pr0hRFZbxQvsYeGj5qmOOiTFhnmgNGcYOh+DPSwHOHZB3bRxrv4YyzTrpk73w=
    on_success: never
    on_failure: always
    on_pull_requests: false
