language: node_js
node_js:
  - '11'
  - '10'
install:
  - yarn install
script:
  - yarn run lint
  - yarn run check
  - yarn run build
before_deploy:
  - cd dist/ngx-sentry
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: h7pB7xGJyuQSztiZM3bJIDQIOwTV/J2yX8AuK2WMoFxHLW5Cho3ntfdj4CX9+IRafcZnCcA1zageWcaGmy/JzUqOMF04TugYmyBgVmBNgGwoX27d2vRgTNOOM71yOIeOQm+LaA8nYmbRJpqSpspPEaSWM+I6mRxTLMMJxnyJHPfRIEDAolB2r1l1Afj+gpmeow4e2hHD8Nb4K79h6+HbxSTCulTfUZ7AwfNqVOJWUQCeHGV88XuBBU72Ez0GGyN4DxBhdAHA+Ao0DV/6gCvlKxRJQauUJorVP2ZIsN9iUrkyBwK759ukBhdnccgZGrPDsvYEqg2gq93rw40EreiXHzCrEGVxImiyxtPZyPqjXbWwoM0Ey+YPhQvfW3hM7O1Fq9wBkqwwEP/8vT6fzex4dAVr4BH+fG3kut1eF5KIiRvbXeNwss5p5nU0F3aVfu4vpEYuFCNVRSwAOlPafyNB/jIZghml2uGFLetqHYS2XWTFewoAhSzffMfmWkAEYJkd3xAWMIeW4VpMDduDc6enSAfMtY/4aOH2RXyoiGnuGMYaWDG442x9OJGAplELKc4IpqMdc3yCVglwhh/1MBd91rbuXMwN4Kw2n3iqGUeU2Tao7/fjTclPa+hM0NBu4fI4YH3AoD06FfotQCEc5n9AT7XM2Ht4EBgoZz8DDZZK2GE=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 11
env:
  global:
    secure: vJ/5/jxEYSaB8BRnazy6vj/IV4ubf6eTKnvP4JVVIcxcWdh+Z0H+L4om5S9284yOf5pL2o/wvmu5NQsEjilCiBSxnxSjVF86P4YU0Volo24sqpqbGBMIhzGODsYee8UOLRhmD0guL4MZfFveq+cYFKiWaMB9eoml7j6TqNselH4BYhmDI5iGzlR/ahRBoa2EZkxngrZhj007Y3LesxhOIM/x0jGkuzCrG30FN62D4RwaYN0rGQ6HJ3zZc3itXxEeyImElMayKExBLDhymJAyG3aSKYANrVzdpmLcqyLLvlODSANZE7exzQP2TwQxY4iPyap1Ma/vPk+SN1vA77LVBSqvWGA4sVKMrKObARnD6eniP9n5Q7haa7pJXf65hvEhl8aIh9YOUJ8XfX9iOfsE/vBuQHdA0IJ5TZpu964vSFXhqUjuw1dyjqnVqLopfbjIl+WaJMNxuRNt9Q8l2OFH7KqDUR+xn15EKgkPan4LBkiwoWCEBx6ANPvba6tugCXCYGBt8bKZWxKpv+IX8E7PqcZ9MLZC1/jr3wSire1ZisYIDdYuGb23oQN24T4U7XAQ0yaUWWSKzaFf2Gm4pbma27PG/+WszlrUzCxjJm/HCnhyH8pW8655n9+uKR5RZI1SZ6VJi+kc4PxqvyUa7+EBbMoF64+zJcWqSZv0p0D07Jo=
notifications:
  slack:
    secure: eWI+L5YntaVGB1ydN2rNeurwBLsTYVMLFYvfPGe67i3pFmvWLJjXW3wrU92sPf8w1/6HvqBk+Dnr1FJDXaRsJzw/9NNqI7kFH2069HSWR5pnfBIQBakr1a6jLt5xxtDgqYex534Ajz1B6GvIq0Gxvk0+FXQIZjdbc6xnC0wEQhq1BKQrsWkx5dVcSIfF3KmUW2KS2qELPp3VHT9hKs/djUsZnEo2VvknDSksMbVReb8Ys2WaHxtJhiBXhYqSVg6VL6AJHJN+MK/CgdSzvygBBC7IymSau4cYWpUemcQfEH+rIxluZj6dfIWnNbdwYbHD45sbs7cy1wdKtCrnR/UgyZ0Y8wDfETkWcv5X37hjKyeTwrpdKdR2xsIJVaNFumcoPB4GTu8RGMvI9CB1j8gxgdXoJ0FLUQ3Wp6WpXYfF7nCpmyvo8bb3CelGcjKbYxs44tAFHtHaZpfML1PKkRHpBs8+DihBbGQkLuxOmYnFHNihCUbbjb5QCx2ufSU6VncbP/MUoqmR2OUgNpUpAc4d0k5UGKOJfqqvx9+44MsIWfHcEsjku1HTeBpZRQvZvqvSzkXmF2PIiKn1oAg8M7ePlC3SAmXkadsKnxdjFPjWxGLK27Pr0hRFZbxQvsYeGj5qmOOiTFhnmgNGcYOh+DPSwHOHZB3bRxrv4YyzTrpk73w=
