version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    target_branch: "develop"
    update_schedule: "live"
    version_requirement_updates: increase_versions
    commit_message:
      prefix: "chore"
      include_scope: true
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
