name: Publish package
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3

      # prepare
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile

      # build
      - run: yarn run lint
      - run: yarn run build

      # publish
      - run: yarn publish
        working-directory: dist/ngx-sentry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # generate release notes
      - name: Generate release notes
        if: startsWith(github.ref, 'refs/tags/v')
        id: changelog
        run: |
          npx standard-changelog -i /dev/null -o CHANGES.md

      # create github release
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          bodyFile: CHANGES.md
          prerelease: ${{ steps.changelog.outputs.status == 'prereleased' }}
          draft: ${{ steps.changelog.outputs.status == 'unreleased' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: README.md,LICENSE.md
